#!/bin/bash

COMPILER="g++"
SOURCE_FOLDER="src"
BUILD_FOLDER="build"
CLASS_FOLDER="src/Classes"
HEADER_FOLDER="src/Headers"
PROJECT_NAME="gl"
LIBRARIES="-lGL -lglfw -lGLEW"

mkdir -p $BUILD_FOLDER
$COMPILER -c $SOURCE_FOLDER/Main.cpp $CLASS_FOLDER/*.cpp
$COMPILER *.o -o $BUILD_FOLDER/$PROJECT_NAME -I $HEADER_FOLDER $LIBRARIES
rm *.o
